'use strict';

const products = [

  // ───── EARBUDS ─────
  {
    name:        "Bolizma Bluetooth Sleep Earbuds with LED Display Charging Case",
    category:    "Earbuds",
    description: "Bluetooth sleep earbuds with LED display charging case for all-night comfort.",
    price:       5879,
    oldPrice:    37548,
    tag:         "popular",
    stock:       50,
    image:       "/images/2.PNG",
    active:      true,
  },
  {
    name:        "itel Earbuds Wireless Bluetooth 5.3 Headphones with Deep Bass",
    category:    "Earbuds",
    description: "Wireless Bluetooth 5.3 earbuds with deep bass and clear call quality.",
    price:       14112,
    oldPrice:    10080,
    tag:         "new",
    stock:       50,
    image:       "/images/2_2.PNG",
    active:      true,
  },
  {
    name:        "Bolizma Sleeping Earbuds Bluetooth 5.4 Earphones TWS",
    category:    "Earbuds",
    description: "Bluetooth 5.4 TWS sleeping earbuds with LED display and ultra-low profile fit.",
    price:       9290,
    oldPrice:    10886,
    tag:         "popular",
    stock:       50,
    image:       "/images/2_3.PNG",
    active:      true,
  },
  {
    name:        "Bolizma Black Wireless Open Ear Earbuds with Bluetooth Air Clip",
    category:    "Earbuds",
    description: "Open ear air clip Bluetooth earbuds with LED digital display charging case.",
    price:       12935,
    oldPrice:    12348,
    tag:         "new",
    stock:       50,
    image:       "/images/2_4.PNG",
    active:      true,
  },
  {
    name:        "Noise Hush ORAIMO Bluetooth Earphones Wireless Gaming",
    category:    "Earbuds",
    description: "ORAIMO wireless gaming earphones with real noise cancellation technology.",
    price:       33869,
    oldPrice:    24192,
    tag:         "popular",
    stock:       50,
    image:       "/images/3_10.PNG",
    active:      true,
  },
  {
    name:        "MingDe Era Wireless Earbuds with Noise Cancelling 30H",
    category:    "Earbuds",
    description: "Wireless earbuds with ENC noise cancelling and 30H long battery life.",
    price:       10372,
    oldPrice:    12348,
    tag:         "new",
    stock:       50,
    image:       "/images/3_10_2.PNG",
    active:      true,
  },
  {
    name:        "Bolizma Wireless In-Ear Bluetooth Earbuds with Charging Case HiFi",
    category:    "Earbuds",
    description: "HiFi wireless in-ear Bluetooth earbuds with LED display charging case.",
    price:       7055,
    oldPrice:    8644,
    tag:         "popular",
    stock:       50,
    image:       "/images/3_10_3.PNG",
    active:      true,
  },
  {
    name:        "Bolizma Wireless Earbuds Bluetooth 5.4 Open Ear",
    category:    "Earbuds",
    description: "Open ear Bluetooth 5.4 wireless earbuds with secure fit and clear sound.",
    price:       9995,
    oldPrice:    10811,
    tag:         "new",
    stock:       50,
    image:       "/images/3_10_4.PNG",
    active:      true,
  },
  {
    name:        "VANIR Open Ear Bluetooth Earbuds with Earhooks 48H",
    category:    "Earbuds",
    description: "Open ear Bluetooth earbuds with secure earhooks and 48H total battery life.",
    price:       12701,
    oldPrice:    60480,
    tag:         "popular",
    stock:       50,
    image:       "/images/Capture_1.PNG",
    active:      true,
  },
  {
    name:        "Bolizma Wireless Earbuds with Digital Display Bluetooth 5.3",
    category:    "Earbuds",
    description: "Bluetooth 5.3 wireless earbuds with digital display and premium sound quality.",
    price:       9407,
    oldPrice:    9878,
    tag:         "new",
    stock:       50,
    image:       "/images/Capture_2.PNG",
    active:      true,
  },
  {
    name:        "Bolizma Sleeping Earbuds Bluetooth 5.4 Earphones TWS",
    category:    "Earbuds",
    description: "TWS sleeping earbuds with Bluetooth 5.4 and ultra-comfortable low-profile design.",
    price:       9290,
    oldPrice:    10886,
    tag:         "popular",
    stock:       50,
    image:       "/images/Capture_3.PNG",
    active:      true,
  },
  {
    name:        "Bolizma Wireless In-Ear Bluetooth Earbuds HiFi Charging Case",
    category:    "Earbuds",
    description: "HiFi in-ear Bluetooth earbuds with fast-charge case and crystal-clear audio.",
    price:       7055,
    oldPrice:    8644,
    tag:         "new",
    stock:       50,
    image:       "/images/Capture_4.PNG",
    active:      true,
  },

  // ───── POWER BANKS ─────
  {
    name:        "Oraimo Traveler 15 Power Bank 20000mAh 15W Type-C Fast Charging",
    category:    "Power Banks",
    description: "Oraimo 20000mAh power bank with 15W fast charging and Type-C input/output.",
    price:       17053,
    oldPrice:    22982,
    tag:         "popular",
    stock:       50,
    image:       "/images/3.PNG",
    active:      true,
  },
  {
    name:        "SUNDASELF Portable Power Bank 20000mAh x2 Dual USB",
    category:    "Power Banks",
    description: "2-pack SUNDASELF 20000mAh portable power banks with dual USB output.",
    price:       18628,
    oldPrice:    24192,
    tag:         "new",
    stock:       50,
    image:       "/images/3_2.PNG",
    active:      true,
  },
  {
    name:        "GDTINA 30000mAh 22.5W Super Fast Charging Power Bank",
    category:    "Power Banks",
    description: "30000mAh power bank with 22.5W super fast charging and built-in cables.",
    price:       17522,
    oldPrice:    26880,
    tag:         "popular",
    stock:       50,
    image:       "/images/3_3.PNG",
    active:      true,
  },
  {
    name:        "Philly 20000mAh Power Charging Bank Portable Charger Ultra Slim",
    category:    "Power Banks",
    description: "Ultra slim Philly 20000mAh power bank with 4 ports including Type-C and micro USB.",
    price:       8980,
    oldPrice:    10319,
    tag:         "new",
    stock:       50,
    image:       "/images/3_4.PNG",
    active:      true,
  },
  {
    name:        "Philly 50000mAh 66W Super Fast Charge Power Bank",
    category:    "Power Banks",
    description: "Philly PD-51 50000mAh power bank with 66W super fast charging and LED display.",
    price:       29988,
    oldPrice:    27569,
    tag:         "popular",
    stock:       50,
    image:       "/images/3_1.PNG",
    active:      true,
  },
  {
    name:        "AVNEX 50000mAh Strong Durable Full Capacity Large Power Bank",
    category:    "Power Banks",
    description: "AVNEX 50000mAh full capacity power bank with built-in cables and fast charging.",
    price:       34642,
    oldPrice:    33754,
    tag:         "new",
    stock:       50,
    image:       "/images/3_2_1.PNG",
    active:      true,
  },
  {
    name:        "Baseus Lipo 20000mAh Power Bank 3A Fast Charging",
    category:    "Power Banks",
    description: "Baseus Lipo 20000mAh power bank with 3A fast charging, 3 outputs and 1 input port, travel-friendly for iOS and Android.",
    price:       21000,
    oldPrice:    29400,
    tag:         "new",
    stock:       50,
    image:       "/images/baseus_lipo_powerbank.PNG",
    active:      true,
  },
  {
    name:        "Oraimo Anifast Power Bank",
    category:    "Power Banks",
    description: "Oraimo Anifast power bank delivering reliable fast charging in a sleek, compact everyday-carry design.",
    price:       21500,
    oldPrice:    30100,
    tag:         "popular",
    stock:       50,
    image:       "/images/oraimo_anifast_powerbank.PNG",
    active:      true,
  },
  {
    name:        "Romoss Power Bank",
    category:    "Power Banks",
    description: "Romoss high-capacity power bank offering dependable backup power for phones and small devices.",
    price:       19469,
    oldPrice:    27257,
    tag:         "new",
    stock:       50,
    image:       "/images/romoss_powerbank.PNG",
    active:      true,
  },
  {
    name:        "Canyon Power Bank",
    category:    "Power Banks",
    description: "Canyon portable power bank with a durable white finish, ideal for daily commutes and travel.",
    price:       25000,
    oldPrice:    35000,
    tag:         "popular",
    stock:       50,
    image:       "/images/canyon_powerbank.PNG",
    active:      true,
  },

  // ───── CLOTHING ─────
  {
    name:        "Jonnie Striped Black Baggy Track Pants",
    category:    "Clothing",
    description: "Stylish black baggy track pants with contrast stripe design for streetwear looks.",
    price:       15876,
    oldPrice:    33600,
    tag:         "popular",
    stock:       50,
    image:       "/images/4.PNG",
    active:      true,
  },
  {
    name:        "Track Striped Baggy Trouser Black",
    category:    "Clothing",
    description: "Baggy black track trousers with bold stripe detailing for casual and street style.",
    price:       12700,
    oldPrice:    25200,
    tag:         "new",
    stock:       50,
    image:       "/images/4_2.PNG",
    active:      true,
  },
  {
    name:        "UNLIMITED Baggy Track Joggers",
    category:    "Clothing",
    description: "Unlimited edition baggy track joggers with wide-leg fit and comfortable waistband.",
    price:       12172,
    oldPrice:    8694,
    tag:         "popular",
    stock:       50,
    image:       "/images/4_3.PNG",
    active:      true,
  },
  {
    name:        "Asake Round Neck T-Shirt",
    category:    "Clothing",
    description: "Trendy round neck T-shirt with relaxed fit for everyday casual wear.",
    price:       10055,
    oldPrice:    16800,
    tag:         "new",
    stock:       50,
    image:       "/images/4_4.PNG",
    active:      true,
  },
  {
    name:        "GALUIN Men's Casual Short-Sleeve Set",
    category:    "Clothing",
    description: "Men's casual short-sleeve sports set with matching top and shorts.",
    price:       13547,
    oldPrice:    20563,
    tag:         "popular",
    stock:       50,
    image:       "/images/4_1.PNG",
    active:      true,
  },
  {
    name:        "Berrykey Men's Pull Over Short Sleeve Polo Vintage Striped",
    category:    "Clothing",
    description: "Vintage striped polo shirt with classic pull-over design and bold color blocking.",
    price:       19016,
    oldPrice:    27166,
    tag:         "new",
    stock:       50,
    image:       "/images/4_1_2.PNG",
    active:      true,
  },
  {
    name:        "Dou-color Men's 2-in-1 Racing Style Set",
    category:    "Clothing",
    description: "Racing-style 2-in-1 men's set with graphic tee and matching shorts.",
    price:       10110,
    oldPrice:    12012,
    tag:         "popular",
    stock:       50,
    image:       "/images/4_1_3.PNG",
    active:      true,
  },
  {
    name:        "Men's Trendy Multi Short Sleeve Shirt Sweatshirts",
    category:    "Clothing",
    description: "Multi-print short sleeve sweatshirt with vibrant African-inspired graphic design.",
    price:       8350,
    oldPrice:    14818,
    tag:         "new",
    stock:       50,
    image:       "/images/4_1_4.PNG",
    active:      true,
  },

  // ───── BAGS ─────
  {
    name:        "NAOT NAOT Plush Love Handbag Shoulder Bag Crossbody",
    category:    "Bags",
    description: "Cute pink plush heart-shaped crossbody handbag with gold chain strap.",
    price:       4759,
    oldPrice:    7866,
    tag:         "popular",
    stock:       50,
    image:       "/images/4_5.PNG",
    active:      true,
  },
  {
    name:        "addigoes Trendy Square Handbag For Women",
    category:    "Bags",
    description: "Trendy square mini handbag in classic black with structured silhouette for women.",
    price:       14110,
    oldPrice:    22295,
    tag:         "new",
    stock:       50,
    image:       "/images/4_6.PNG",
    active:      true,
  },
  {
    name:        "High Quality Padded Laptop Bag Laptop Pouch Case Sleeve",
    category:    "Bags",
    description: "Padded laptop sleeve bag with shoulder strap for laptops up to 15.6 inches.",
    price:       9995,
    oldPrice:    10920,
    tag:         "popular",
    stock:       50,
    image:       "/images/4_7.PNG",
    active:      true,
  },
  {
    name:        "GALUIN Waterproof Anti-theft Men's Backpack For Laptop",
    category:    "Bags",
    description: "GALUIN waterproof anti-theft backpack with USB charging port for laptop use.",
    price:       16088,
    oldPrice:    19450,
    tag:         "new",
    stock:       50,
    image:       "/images/4_8.PNG",
    active:      true,
  },
  {
    name:        "Men Sling Bag Pack With Lock Waterproof Anti-Theft Chest Bag",
    category:    "Bags",
    description: "Waterproof anti-theft sling chest bag with combination lock for men.",
    price:       11096,
    oldPrice:    17278,
    tag:         "popular",
    stock:       50,
    image:       "/images/4_1_1.PNG",
    active:      true,
  },
  {
    name:        "Single Laptop Table",
    category:    "Bags",
    description: "Portable adjustable laptop table for bed and sofa use with smooth rolling wheels.",
    price:       41160,
    oldPrice:    29400,
    tag:         "new",
    stock:       50,
    image:       "/images/4_1_2_1.PNG",
    active:      true,
  },
  {
    name:        "3 In 1 Multi Functional Backpack With USB Slot",
    category:    "Bags",
    description: "3-in-1 backpack set with USB charging port, matching shoulder bag and wallet.",
    price:       14495,
    oldPrice:    18144,
    tag:         "popular",
    stock:       50,
    image:       "/images/4_1_3_1.PNG",
    active:      true,
  },
  {
    name:        "3-in-1 Productivity Offer: Premium Felt Laptop Bag with Stands",
    category:    "Bags",
    description: "Premium 3-in-1 felt laptop bag bundled with aluminium phone and laptop stands.",
    price:       27047,
    oldPrice:    25200,
    tag:         "new",
    stock:       50,
    image:       "/images/4_1_4_1.PNG",
    active:      true,
  },
  {
    name:        "High Quality Waterproof Backpack Laptop Bag with Padded Laptop",
    category:    "Bags",
    description: "Waterproof padded laptop backpack with multiple compartments and sleek design.",
    price:       15388,
    oldPrice:    16800,
    tag:         "popular",
    stock:       50,
    image:       "/images/5_2_2.PNG",
    active:      true,
  },

  // ───── GAMING ─────
  {
    name:        "GtyGo Wired Gaming Mouse 7 Functional Keys RGB Light",
    category:    "Gaming",
    description: "7-button wired gaming mouse with RGB lighting and adjustable DPI settings.",
    price:       4616,
    oldPrice:    9072,
    tag:         "popular",
    stock:       50,
    image:       "/images/4_9.PNG",
    active:      true,
  },
  {
    name:        "Mechanical Keyboard 61-Key RGB Backlit Blue Switch Wired Gaming",
    category:    "Gaming",
    description: "Compact 61-key mechanical gaming keyboard with RGB backlight and blue switches.",
    price:       25872,
    oldPrice:    22739,
    tag:         "new",
    stock:       50,
    image:       "/images/4_9_2.PNG",
    active:      true,
  },
  {
    name:        "Wired Luminescent Gaming Mouse/Mice Computer",
    category:    "Gaming",
    description: "High-precision wired gaming mouse with luminescent RGB design and ergonomic grip.",
    price:       6428,
    oldPrice:    9532,
    tag:         "popular",
    stock:       50,
    image:       "/images/4_9_3.PNG",
    active:      true,
  },
  {
    name:        "WIRELESS RGB Gaming Mouse DPI Ergonomic Mice PC",
    category:    "Gaming",
    description: "Wireless RGB ergonomic gaming mouse with adjustable DPI and silent click buttons.",
    price:       14700,
    oldPrice:    13356,
    tag:         "new",
    stock:       50,
    image:       "/images/4_9_4.PNG",
    active:      true,
  },
  {
    name:        "Best Controllers Game Pads USB For PC & Laptops Windows",
    category:    "Gaming",
    description: "Dual USB gamepad controller compatible with PC and laptops running Windows.",
    price:       11525,
    oldPrice:    10919,
    tag:         "popular",
    stock:       50,
    image:       "/images/5.PNG",
    active:      true,
  },
  {
    name:        "RGB Smart Wired Gaming Keyboard PC Laptop Gaming",
    category:    "Gaming",
    description: "Full-size RGB wired gaming keyboard with smart lighting effects and multimedia keys.",
    price:       29400,
    oldPrice:    58800,
    tag:         "new",
    stock:       50,
    image:       "/images/5_1.PNG",
    active:      true,
  },
  {
    name:        "8pcs Mobile Gaming Finger Sleeves Thumb Gloves For Mobile",
    category:    "Gaming",
    description: "8-piece anti-sweat mobile gaming finger sleeves for smooth touchscreen control.",
    price:       11748,
    oldPrice:    16800,
    tag:         "popular",
    stock:       50,
    image:       "/images/5_2.PNG",
    active:      true,
  },
  {
    name:        "4 Pcs Gaming Finger Sleeves Game Gloves Thumb Finger Cots",
    category:    "Gaming",
    description: "4-piece gaming finger cots for precise swipe and tap control on mobile games.",
    price:       3704,
    oldPrice:    4200,
    tag:         "new",
    stock:       50,
    image:       "/images/5_2_3.PNG",
    active:      true,
  },
  {
    name:        "Finger Thumb Mobile Gaming Sleeves",
    category:    "Gaming",
    description: "1-pair finger thumb gaming sleeves with anti-sweat breathable fabric for mobile gaming.",
    price:       4116,
    oldPrice:    4200,
    tag:         "popular",
    stock:       50,
    image:       "/images/5_2_4.PNG",
    active:      true,
  },
  {
    name:        "Bluetooth Wireless Receiver Transmitter Audio Adapter",
    category:    "Gaming",
    description: "Bluetooth 5.3 wireless audio receiver and transmitter adapter for TVs and speakers.",
    price:       10466,
    oldPrice:    7560,
    tag:         "new",
    stock:       50,
    image:       "/images/4_1_5.PNG",
    active:      true,
  },
  {
    name:        "2IN1 Bluetooth Wireless Receiver Transmitter Audio Adapter",
    category:    "Gaming",
    description: "2-in-1 Bluetooth audio adapter that works as both receiver and transmitter.",
    price:       10466,
    oldPrice:    13356,
    tag:         "popular",
    stock:       50,
    image:       "/images/4_1_6.PNG",
    active:      true,
  },
  {
    name:        "Universal Wireless Bluetooth Receiver & Transmitter Audio",
    category:    "Gaming",
    description: "Universal Bluetooth 5.3 audio transmitter and receiver for any wired audio device.",
    price:       10231,
    oldPrice:    10836,
    tag:         "new",
    stock:       50,
    image:       "/images/4_1_7.PNG",
    active:      true,
  },
  {
    name:        "Sony PlayStation 2 Analog Dual Shock 2 Controller",
    category:    "Gaming",
    description: "Official Sony PS2 analog dual shock controller with responsive analog sticks and vibration feedback.",
    price:       7500,
    oldPrice:    10500,
    tag:         "popular",
    stock:       50,
    image:       "/images/ps2_dualshock.PNG",
    active:      true,
  },
  {
    name:        "Sony PS3 Dual Shock 3 Wireless Game Pad - White",
    category:    "Gaming",
    description: "Wireless Sony PS3 Dual Shock 3 controller in white with SIXAXIS motion sensing and rechargeable battery.",
    price:       7999,
    oldPrice:    11199,
    tag:         "new",
    stock:       50,
    image:       "/images/ps3_dualshock.PNG",
    active:      true,
  },

  // ───── LIGHTERS ─────
  {
    name:        "Rechargeable Electric Arc Ignitor with USB Cord for Gas Stoves",
    category:    "Lighters",
    description: "Rechargeable electric arc ignitor for gas stoves, candles, and BBQ grills.",
    price:       6350,
    oldPrice:    4536,
    tag:         "popular",
    stock:       50,
    image:       "/images/4_5_1.PNG",
    active:      true,
  },
  {
    name:        "Rechargeable Electric Arc Ignitor Lifetime Warranty",
    category:    "Lighters",
    description: "Long-reach electric arc lighter with lifetime warranty and USB recharging.",
    price:       4351,
    oldPrice:    3108,
    tag:         "new",
    stock:       50,
    image:       "/images/4_5_2.PNG",
    active:      true,
  },
  {
    name:        "Rechargeable Electric Arc Ignitor for Gas Stoves Colorful",
    category:    "Lighters",
    description: "Colorful rechargeable electric arc ignitor with flexible neck for kitchen use.",
    price:       4339,
    oldPrice:    3100,
    tag:         "popular",
    stock:       50,
    image:       "/images/4_5_3.PNG",
    active:      true,
  },
  {
    name:        "Rechargeable Electric Arc Ignitor for Gas Stoves Pink",
    category:    "Lighters",
    description: "Pink rechargeable electric arc ignitor with long neck for safe and easy lighting.",
    price:       5879,
    oldPrice:    4199,
    tag:         "new",
    stock:       50,
    image:       "/images/4_5_4.PNG",
    active:      true,
  },

  // ───── WATCHES ─────
  {
    name:        "BINBOND Men's Watch Fashion Waterproof Sport Quartz Business",
    category:    "Watches",
    description: "BINBOND men's waterproof sport quartz business watch with leather strap.",
    price:       10346,
    oldPrice:    9773,
    tag:         "popular",
    stock:       50,
    image:       "/images/5_2_1.PNG",
    active:      true,
  },
  {
    name:        "WABOOC Men's Luxury Stainless Steel Quartz Watch Luminous",
    category:    "Watches",
    description: "WABOOC luxury stainless steel quartz watch with luminous hands and date display.",
    price:       19966,
    oldPrice:    26599,
    tag:         "new",
    stock:       50,
    image:       "/images/5_1_1.PNG",
    active:      true,
  },
  {
    name:        "Glow-in-the-Dark Rhinestone LED Student Couple Quartz Watch",
    category:    "Watches",
    description: "Glow-in-the-dark rhinestone LED quartz watch for students and couples.",
    price:       6691,
    oldPrice:    7747,
    tag:         "popular",
    stock:       50,
    image:       "/images/5_1_2.PNG",
    active:      true,
  },
  {
    name:        "BINLIHUAN Men's Business Quartz Watch Luxury Skull Style",
    category:    "Watches",
    description: "Punk-style luxury skull quartz watch with genuine leather strap for men.",
    price:       12965,
    oldPrice:    30870,
    tag:         "new",
    stock:       50,
    image:       "/images/5_1_3.PNG",
    active:      true,
  },

  // ───── SMARTWATCHES ─────
  {
    name:        "Smart Sports Watch with Heart Rate Monitor",
    category:    "Smartwatches",
    description: "Advanced smartwatch with heart rate monitoring, fitness tracking, and blood pressure sensor.",
    price:       4875,
    oldPrice:    7800,
    tag:         "popular",
    stock:       50,
    image:       "/images/8_4.PNG",
    active:      true,
  },
  {
    name:        "Premium Smartwatch Case Protector - Rose Gold",
    category:    "Smartwatches",
    description: "Durable protective case for smartwatch in elegant rose gold finish with screen guard.",
    price:       2100,
    oldPrice:    3360,
    tag:         "new",
    stock:       50,
    image:       "/images/8_5.PNG",
    active:      true,
  },
  {
    name:        "Premium Smartwatch Case Protector - Silver",
    category:    "Smartwatches",
    description: "Premium protective case for smartwatch in silver with tempered glass screen protector.",
    price:       2100,
    oldPrice:    3360,
    tag:         "popular",
    stock:       50,
    image:       "/images/8_6.PNG",
    active:      true,
  },
  {
    name:        "Fitness Smartwatch with LED Display",
    category:    "Smartwatches",
    description: "Feature-rich fitness smartwatch with LED display, multi-sport modes, and health tracking.",
    price:       4800,
    oldPrice:    7680,
    tag:         "new",
    stock:       50,
    image:       "/images/8_7.PNG",
    active:      true,
  },
  {
    name:        "Rugged Smartwatch with Interchangeable Band",
    category:    "Smartwatches",
    description: "Durable rugged smartwatch with interchangeable yellow band and outdoor features.",
    price:       6000,
    oldPrice:    9600,
    tag:         "popular",
    stock:       50,
    image:       "/images/8_8.PNG",
    active:      true,
  },
  {
    name:        "Compact Smartwatch with Health Monitoring",
    category:    "Smartwatches",
    description: "Lightweight compact smartwatch with comprehensive health monitoring and fitness tracking.",
    price:       4200,
    oldPrice:    6720,
    tag:         "new",
    stock:       50,
    image:       "/images/8_9.PNG",
    active:      true,
  },
  {
    name:        "Smartwatch with Stylish Pink Band",
    category:    "Smartwatches",
    description: "Elegant smartwatch with pink band, -35% discount on health monitoring features.",
    price:       3720,
    oldPrice:    5952,
    tag:         "popular",
    stock:       50,
    image:       "/images/8_10.PNG",
    active:      true,
  },
  {
    name:        "Smartwatch with Gray Band and LED Display",
    category:    "Smartwatches",
    description: "Modern smartwatch with gray band, LED display, and comprehensive fitness tracking features.",
    price:       3960,
    oldPrice:    6336,
    tag:         "new",
    stock:       50,
    image:       "/images/8_11.PNG",
    active:      true,
  },

  // ───── ROUTERS ─────
  {
    name:        "5G WiFi Router with High Speed Connectivity",
    category:    "Routers",
    description: "Advanced 5G WiFi router for fast and stable internet connectivity throughout your space.",
    price:       13200,
    oldPrice:    21120,
    tag:         "popular",
    stock:       50,
    image:       "/images/9.PNG",
    active:      true,
  },
  {
    name:        "MTN 5G Router - Premium Model",
    category:    "Routers",
    description: "MTN official 5G router with 100gb data bundle and premium connectivity features.",
    price:       6720,
    oldPrice:    10752,
    tag:         "new",
    stock:       50,
    image:       "/images/9_1.PNG",
    active:      true,
  },
  {
    name:        "MTN 5G Booster - Enhanced Coverage",
    category:    "Routers",
    description: "MTN 5G signal booster with -12% discount for extended network coverage.",
    price:       5880,
    oldPrice:    9408,
    tag:         "popular",
    stock:       50,
    image:       "/images/9_2.PNG",
    active:      true,
  },
  {
    name:        "MTN 5G Signal Enhancer",
    category:    "Routers",
    description: "Compact MTN 5G signal enhancer with -5% discount for optimal network performance.",
    price:       5520,
    oldPrice:    8832,
    tag:         "new",
    stock:       50,
    image:       "/images/9_3.PNG",
    active:      true,
  },
  {
    name:        "Xiaomi Mesh System AC1200 EU White",
    category:    "Routers",
    description: "Dual-band Wi-Fi mesh system up to 1200Mbps, seamlessly covers your whole home and connects up to 254 devices.",
    price:       28800,
    oldPrice:    40320,
    tag:         "popular",
    stock:       50,
    image:       "/images/xiaomi_mesh_ac1200.PNG",
    active:      true,
  },
  {
    name:        "MTN Ops Router Powerbank K10 - Original 5G Router",
    category:    "Routers",
    description: "Original MTN Ops K10 5G router with built-in powerbank function for on-the-go connectivity.",
    price:       17000,
    oldPrice:    23800,
    tag:         "new",
    stock:       50,
    image:       "/images/mtn_router_powerbank_k10.PNG",
    active:      true,
  },
  {
    name:        "MTN CAT4 K12 4G LTE Router + Free 50GB Data SIM",
    category:    "Routers",
    description: "MTN official CAT4 K12 4G LTE router bundled with a free 50GB data SIM for instant home internet.",
    price:       15000,
    oldPrice:    21000,
    tag:         "popular",
    stock:       50,
    image:       "/images/mtn_cat4_k12_router.PNG",
    active:      true,
  },
  {
    name:        "Mifa Universal 4G LTE Pocket Mifi Mobile WiFi Hotspot Router",
    category:    "Routers",
    description: "Built for Nigerian networks, this universal pocket mifi works seamlessly across all major providers for total network freedom.",
    price:       22944,
    oldPrice:    32122,
    tag:         "new",
    stock:       50,
    image:       "/images/mifa_pocket_mifi.PNG",
    active:      true,
  },
  {
    name:        "USB Type-C to DC Power Line Cable for Router/Powerbank",
    category:    "Routers",
    description: "USB-C to DC 20V round port power cable with built-in PD decoy chip, supports 9V/12V fast charging for routers and power banks.",
    price:       4999,
    oldPrice:    6999,
    tag:         "popular",
    stock:       50,
    image:       "/images/usbc_powerline_cable.PNG",
    active:      true,
  },
  {
    name:        "Glo 4G LTE MiFi Pocket Mobile WiFi with Free 30GB",
    category:    "Routers",
    description: "Glo-branded 4G LTE pocket MiFi device bundled with a free 30GB data allowance for portable home or office internet.",
    price:       21120,
    oldPrice:    29568,
    tag:         "new",
    stock:       50,
    image:       "/images/glo_4g_mifi.PNG",
    active:      true,
  },
  {
    name:        "Universal USB 4G LTE WiFi Hotspot Modem - All Networks",
    category:    "Routers",
    description: "Insert any network SIM card to turn this USB modem into a wireless 4G LTE router, compatible with all Nigerian networks.",
    price:       19899,
    oldPrice:    27859,
    tag:         "popular",
    stock:       50,
    image:       "/images/universal_4g_hotspot_modem.PNG",
    active:      true,
  },
  {
    name:        "MTN CAT4 K12 4G LTE Router + Free 50GB Data Sim Bundle",
    category:    "Routers",
    description: "Compact MTN CAT4 K12 4G LTE router with a bundled 50GB data SIM, ready to use out of the box.",
    price:       9120,
    oldPrice:    12768,
    tag:         "new",
    stock:       50,
    image:       "/images/mtn_cat4_k12_bundle.PNG",
    active:      true,
  },
  {
    name:        "Xiaomi Mi Router 4C (White)",
    category:    "Routers",
    description: "Mi Router 4C with 4 antennas for wide, stable Wi-Fi coverage, 300Mbps high-speed Wi-Fi and app-controlled parental settings.",
    price:       14700,
    oldPrice:    20580,
    tag:         "popular",
    stock:       50,
    image:       "/images/mi_router_4c.PNG",
    active:      true,
  },
  {
    name:        "4G LTE USB MiFi/UFI 150Mbps Modem Stick - Portable Wireless",
    category:    "Routers",
    description: "Portable 4G LTE USB MiFi/UFI modem stick delivering up to 150Mbps wireless speeds for laptops and PCs.",
    price:       15381,
    oldPrice:    21533,
    tag:         "new",
    stock:       50,
    image:       "/images/4g_mifi_modem_stick.PNG",
    active:      true,
  },
  {
    name:        "4G LTE Wireless USB MiFi/UFI Dongle Mobile Broadband",
    category:    "Routers",
    description: "Compact 4G LTE wireless USB dongle providing instant mobile broadband for any network SIM.",
    price:       14499,
    oldPrice:    20299,
    tag:         "popular",
    stock:       50,
    image:       "/images/4g_mifi_dongle.PNG",
    active:      true,
  },

  // ───── PC GAMES ─────
  {
    name:        "BLUR Racing PC Game",
    category:    "PC Games",
    description: "Intense arcade racing game with explosive power-ups and wheel-to-wheel combat.",
    price:       5400,
    oldPrice:    8640,
    tag:         "popular",
    stock:       50,
    image:       "/images/10_1.PNG",
    active:      true,
  },
  {
    name:        "Call of Duty: Modern Warfare PC Game",
    category:    "PC Games",
    description: "Modern Warfare edition with immersive campaign and multiplayer action on PC.",
    price:       5400,
    oldPrice:    8640,
    tag:         "new",
    stock:       50,
    image:       "/images/10_2.PNG",
    active:      true,
  },
  {
    name:        "Call of Duty: Day Zero Edition PC Game",
    category:    "PC Games",
    description: "Exclusive Day Zero Edition of Call of Duty with premium early access content.",
    price:       5400,
    oldPrice:    8640,
    tag:         "popular",
    stock:       50,
    image:       "/images/10_3.PNG",
    active:      true,
  },
  {
    name:        "Call of Duty: Black Ops PC Game",
    category:    "PC Games",
    description: "Black Ops series with intense action, rated 18+ for mature audiences on PC.",
    price:       5400,
    oldPrice:    8640,
    tag:         "new",
    stock:       50,
    image:       "/images/10_4.PNG",
    active:      true,
  },
  {
    name:        "PES 2023 Football Life PC Game",
    category:    "PC Games",
    description: "Pro Evolution Soccer 2023 with updated rosters and realistic football gameplay.",
    price:       7200,
    oldPrice:    11520,
    tag:         "popular",
    stock:       50,
    image:       "/images/10_5.PNG",
    active:      true,
  },
  {
    name:        "GTA V - Grand Theft Auto PC Game",
    category:    "PC Games",
    description: "Grand Theft Auto V - Epic open-world action game for PC with unmatched gameplay.",
    price:       8892,
    oldPrice:    14227,
    tag:         "popular",
    stock:       50,
    image:       "/images/10.PNG",
    active:      true,
  },

  // ───── BEAUTY ─────
  {
    name:        "Premium Cosmetics Storage Organizer 4-Tier",
    category:    "Beauty",
    description: "Multi-compartment cosmetics organizer with 4 tiers, -50% discount on storage solutions.",
    price:       7200,
    oldPrice:    11520,
    tag:         "popular",
    stock:       50,
    image:       "/images/11.PNG",
    active:      true,
  },
  {
    name:        "Hair Treatment Mask - Orange Label",
    category:    "Beauty",
    description: "Professional hair treatment mask with deep conditioning formula, -25% discount available.",
    price:       4440,
    oldPrice:    7104,
    tag:         "new",
    stock:       50,
    image:       "/images/11_1.PNG",
    active:      true,
  },
  {
    name:        "Cosmetics Storage Box with Drawer",
    category:    "Beauty",
    description: "Elegant white cosmetics storage organizer with pull-out drawer, -50% off selected items.",
    price:       7200,
    oldPrice:    11520,
    tag:         "popular",
    stock:       50,
    image:       "/images/11_2.PNG",
    active:      true,
  },
  {
    name:        "Hair Growth Serum Premium Formula",
    category:    "Beauty",
    description: "Advanced hair growth serum with natural ingredients for stronger, healthier hair.",
    price:       3420,
    oldPrice:    5472,
    tag:         "new",
    stock:       50,
    image:       "/images/11_3.PNG",
    active:      true,
  },
  {
    name:        "False Eyelashes Set - 10 Pairs",
    category:    "Beauty",
    description: "Professional false eyelashes bundle with 10 pairs, -8% discount on bulk purchases.",
    price:       2430,
    oldPrice:    3888,
    tag:         "popular",
    stock:       50,
    image:       "/images/11_4.PNG",
    active:      true,
  },
  {
    name:        "24K Gold Face Cream - GUAN JING",
    category:    "Beauty",
    description: "Luxury 24K gold infused face cream for radiant skin, -31% discount this month.",
    price:       4200,
    oldPrice:    6720,
    tag:         "new",
    stock:       50,
    image:       "/images/11_6.PNG",
    active:      true,
  },
  {
    name:        "Premium Face Moisturizer Cream",
    category:    "Beauty",
    description: "Hydrating facial cream with natural moisturizers for smooth, glowing skin.",
    price:       3360,
    oldPrice:    5376,
    tag:         "popular",
    stock:       50,
    image:       "/images/11_5.PNG",
    active:      true,
  },
  {
    name:        "Portable Cosmetics Travel Bag - Blue Pattern",
    category:    "Beauty",
    description: "Stylish blue patterned travel cosmetics bag with multiple compartments for organized beauty storage.",
    price:       4320,
    oldPrice:    6912,
    tag:         "new",
    stock:       50,
    image:       "/images/11_7.PNG",
    active:      true,
  },
];

module.exports = products;
